### ISSUE TITLE
Panic when there are several different declarations

### ISSUE THREAD

**Issue by 3timeslazy** [mununki/gqlmerge#21]
Hi! I want to offer a new feature - check the type's fields when the type has been declared 2 or more times. And if there is a difference between the declarations - panic.

Example:
```graphql 
# FileOne.gql
type Type {
    Field: String
    OneMoreField: String
}

# FileTwo.gql
# another declaration - panic
type Type {
    Field: String
}
```

**Comment by mununki** [comment]
I got your point. Good idea. I'll work on it.

**Comment by mununki** [comment]
@3timeslazy Sorry for my late work, but I've been busy for job searching and serial interviews. 😉
Please check PR #22. I hope to have your feedback.

**Comment by mununki** [comment]
@3timeslazy I'm closing this issue, please reopen if you have any further suggestion.
