### ISSUE TITLE
don't strip comments

### ISSUE THREAD

**Issue by agnewp** [mununki/gqlmerge#24]
comments are used as descriptions in the older syntax and you are effectively removing all self documentation capability from GQL. I find myself wanting to use this but not being able to.

**Comment by agnewp** [comment]
comments are used as descriptions in the older syntax and you are effectively removing all self documentation capability from GQL.  I find myself wanting to use this but not being able to.

**Comment by mununki** [comment]
@agnewp Just to know clear, Is it the same issue to #23? If not, can you give me a sample code to reproduce it?

**Comment by agnewp** [comment]
this is only slighly related to issue 23, but NOT the same

to reproduce, add a comment line to any file and the post-merge result does NOT include that comment line
in a slightly older version of the GQL spec, comment lines next to the fields are used as description meta data. the spec parser i am using supports both this comment line syntax as well as what is mentioned in #23.

so to summarize, if you simply strip out comments when merging GQL files, you might actually be stripping out things that are meant to be self documentation.

does that make sense?

**Comment by mununki** [comment]
Sorry for the huge delay. It totally makes sense to me.

Actually, `gqlmerge` is using a go scanner for lexing and parsing the GraphQL SDL. So the description is tokenized as a string first. In order to resolve this, the best way is to make a custom scanner to tokenize. It will take some time to fix it. #31

**Comment by mununki** [comment]
Sorry for the huge delay, I've released a fixed version that doesn't strip descriptions and comments. Can you test with https://github.com/mununki/gqlmerge/releases/tag/v0.2.9?

**Comment by mununki** [comment]
As of v0.2.9, it's been fixed to not strip description and comment, so closing the issue. If you have any issues, please reopen it.
