### ISSUE TITLE
Merge identical scalars

### ISSUE THREAD

**Issue by gurre** [mununki/gqlmerge#25]
Merging several files with the same scalar produces an error.

```
panic: Duplicated Scalars: Int64(rpc/service.pb.graphqls, 4:8) and (rpc/service.pb.graphqls, 13:8)
```

**Comment by mununki** [comment]
Hi,

Sorry for asking your part of graphQL schema which has the conflict to help myself to debug my code?

**Comment by mununki** [comment]
If you can provide a sample duplicated Scalars that crashes, we'll try to find the cause.

**Comment by mununki** [comment]
stale
