### ISSUE TITLE
Support for implementing multiple interfaces

### ISSUE THREAD

**Issue by kainosnoema** [mununki/gqlmerge#26]
`gqlmerge` doesn't seem to support implementing multiple interfaces (`... implements X & Y`), which is a common practice especially with Relay-style schemas. For example, this doesn't parse, panics with `unexpected "&", expected "{"`:

```graphql
interface Node {
  id: ID!
}

interface Person implements Node {
  id: ID!
  name: String!
  age: Int!
}

type Student implements Node & Person {
  id: ID!
  name: String!
  age: Int!
  universityName: String!
}
```

I'm happy to take a stab at implementation if it's not a priority, just wanted to raise the issue first and get feedback.

**Comment by mununki** [comment]
The mentioned spec is not supported as you raised. Thank you for PR 👍
