### ISSUE TITLE
Provide linux binary releases

### ISSUE THREAD

**Issue by stephenh** [mununki/gqlmerge#28]
I was hoping to use gqlmerge from a github action to merge some `*.graphql` files (before passing them into graphql-inspector).

So I was going to just `wget` the latest binary and run it, but looks like it's probably the Mac binary? 

(Admittedly, I'm not really sure what platform it is, just that it doesn't look like x64 linux?)

Thanks!

**Comment by mununki** [comment]
Hi. Actually it is the darwin binary.
Do you want a linux binary for github action? What matrix os are you going to use? ubuntu?

**Comment by mununki** [comment]
Here is the binary for ubuntu https://github.com/mattdamon108/gqlmerge/releases/tag/v0.2.4 I hope this can help you.

**Comment by stephenh** [comment]
Wow, yep that works great! And yep, I'm using ubuntu; I'm basically trying to do this:

https://github.com/kamilkisiela/graphql-inspector/issues/1978#issuecomment-1077276122

But instead of using ~4 lines of node/JavaScript that require a package.json + npm i, just use a binary like `gqlmerge`.

I ran into one bump that I'll file a separate issue for, but once I get `graphql-inspector` working on our codebase w/`gqlmerge`, I'm going to update that issue with the snippet that works, in case others always want to use `gqlmerge` instead of the node scripting approach.

Thanks for the amazingly fast response!

**Comment by mununki** [comment]
I polished my Github actions for release. https://github.com/mattdamon108/gqlmerge/releases/tag/v0.2.4
I hope this change doesn't make additional work to use my release for your project.

**Comment by tobiasdiez** [comment]
@stephenh did you managed to combine graphql-inspector and gqlmerge? Would be nice to see your solution!

**Comment by stephenh** [comment]
@tobiasdiez no :-/ we still don't have graphql-inspector running against our codebase, b/c we really want to use that GitHub action and b/c it pulls files from the GitHub API, we can't merge both the _current_ schema files and the _previous_ files w/o (AFAIU) fundamentally how the action works, like this solution:

https://github.com/kamilkisiela/graphql-inspector/issues/1978#issuecomment-1077731380

Honestly I've considered just checking in a `schema.graphql` that is our `schema/*.graphql` files combined, directly into git, even though it's not necessary, just so that graphql-inspector would have a single file to look at, across commits. :-/

Haven't done that yet, but getting close b/c it just seems most pragmatic at this point.

**Comment by mununki** [comment]
If you need any support from me, let me know. Cheers! Good luck!
