### ISSUE TITLE
Panic on comments in inputs

### ISSUE THREAD

**Issue by stephenh** [mununki/gqlmerge#29]
We have comments in some `input`s like:

```
input SaveAuthorInput {
  id: ID
  "deprecated: ...rationale..."
  firstName: String
  """
  longer deprecated comment
  """
  lastName: String
}
```

And currently looks like `gqlmerge` doesn't expect them and `panic`s with:

```
unexpected """", expected Ident
```

**Comment by mununki** [comment]
Yes, it is a known issue, but I didn't fix it yet. I'll put some resources on it soon.

**Comment by mununki** [comment]
I finally fix this issue, not to panic for descriptions. But still, it doesn't parse the descriptions and write them down into merged schema. I think it is a quite bigger task than I thought initially, regarding #30 #31 

Please find the latest version for this issue.
https://github.com/mattdamon108/gqlmerge/releases/tag/v0.2.5

**Comment by stephenh** [comment]
Hey @mattdamon108 , cool, for our use case, it's perfectly fine to drop the descriptions. It looks like this #29 is resolved, but yep we have some multi-line comments as well, so I'll sub to #30. Thanks!

**Comment by mununki** [comment]
Sorry for the huge delay, I've released a fixed version that doesn't strip descriptions and comments. Can you test with https://github.com/mununki/gqlmerge/releases/tag/v0.2.9?

**Comment by stephenh** [comment]
Hi @mununki ! Really appreciate the fix! We ended up finding another way to get our GQL files merged, I think just the right incantation of the Node library we were already using, but will definitely keep this in mind if we end up needing to do this again. Thanks!

**Comment by mununki** [comment]
@stephenh Thanks!
