### ISSUE TITLE
input as a Mutation parameter name does not work

### ISSUE THREAD

**Issue by digiz3d** [mununki/gqlmerge#37]
Hi!

When a mutation has a parameter named `input`,
running `go run . test/*.graphql test/generated.graphql` panics:
```
panic: lib.Error("/xxx/gqlmerge/test/CreateLog-ko.graphql:6:18: unexpected "input"")
```
My hypothesis is that the lexer sees an "input" keyword without knowing that it should not look for keywords when it is located in parameters.

Sorry, I'm not experienced enough with parsing at the moment to implement a fix, so the least I could do is give you [a reproducible example here](https://github.com/digiz3d/gqlmerge/tree/master).

Have a good day !

**Comment by mununki** [comment]
Thank you for open the issue!
Can you make a PR to add your tests? Then I'll look into the case to fix it.

**Comment by digiz3d** [comment]
Sure! sorry for the delayed response ! 
Here you go https://github.com/mununki/gqlmerge/pull/38

**Comment by mununki** [comment]
I think it is fixed. Can you test with v0.2.10?

**Comment by digiz3d** [comment]
It's indeed fixed for input name ! Thank you for fixing it 👍

Now there is a similar problem with this kind of GraphQL definition:
```gql
type SomePayload {
  userId: ID!
  type: SomeOtherStuff!
}
```

As you can guess, the inner `type` is considered as a token, similar problem 😬 
Want me to open a new issue for this problem?

**Comment by mununki** [comment]
> It's indeed fixed for input name ! Thank you for fixing it 👍
> 
> Now there is a similar problem with this kind of GraphQL definition:
> 
> ```graphql
> type SomePayload {
>   userId: ID!
>   type: SomeOtherStuff!
> }
> ```
> 
> As you can guess, the inner `type` is considered as a token, similar problem 😬 Want me to open a new issue for this problem?

Sure! Thank you!
