### ISSUE TITLE
type as a property name does not work

### ISSUE THREAD

**Issue by digiz3d** [mununki/gqlmerge#44]
As talked about in https://github.com/mununki/gqlmerge/issues/37
A type like
```graphql
type SomePayload {
  type: String!
}
```
Will panic because of a GraphQL parsing error when it encounters the inner `type` keyword

Here is the PR https://github.com/mununki/gqlmerge/pull/43 with reproducible example 👌

**Comment by mununki** [comment]
Thanks! Will fix soon.

**Comment by mununki** [comment]
I believe that It is fixed in v0.2.11. Can you test with it?

**Comment by digiz3d** [comment]
Indeed this specific issue is now gone !
