### ISSUE TITLE
Adding subscription without schema

### ISSUE THREAD

**Issue by MarcosBustamante** [mununki/gqlmerge#46]
On my schema, I do not have defined any subscriptions. However, the merge process is adding a subscription on my schema:
```
schema {
  query: Query
  mutation: Mutation
  subscription: Subscription
}
```

But the merged file generated doesn't define the `Subscription` type. The merge should only add the subscription inside the schema if it exists

**Comment by mununki** [comment]
Thank you for opening the issue. I'll fix it soon.

**Comment by mununki** [comment]
Can you test the latest v0.2.12? I think it is fixed.

**Comment by MarcosBustamante** [comment]
Sure, I will test today :)

**Comment by MarcosBustamante** [comment]
I just tested and it worked =D

**Comment by mununki** [comment]
> I just tested and it worked =D

Thanks!
