### ISSUE TITLE
duplicated types error

### ISSUE THREAD

**Issue by MarcosBustamante** [mununki/gqlmerge#48]
In one file I have and auto gen type:
```
type Person implements Node {
  id: ID!
  createTime: Time!
  updateTime: Time!
  name: String!
}
```

in another file I am adding an extra field that I need to calculate the value:
```
extend type Person {
  hasCar: Boolean!
}
```

And I am getting this error:
```
panic: lib.Error("Duplicated Types: Person(graph/platform/person.graphql:1:12) and (graph/platform/schema.graphql:17:5)")
```

**Comment by mununki** [comment]
It doesn't yet support extend type, but I'll fix that soon.

**Comment by mununki** [comment]
Sorry for the late return. The Object type extension is something I'm not familiar with as I've not used it in a product or project. I understood it from the spec documentation https://spec.graphql.org/October2021/#sec-Object-Extensions.
I have one question: is it okay for Object type extensions added from multiple files to exist in one GraphQL schema after being merged? That's how I understand it according to the spec docs, but I'm wondering if that's correct. For example:
```graphql
# from A.graphql
type Person implements Node {
  id: ID!
  createTime: Time!
  updateTime: Time!
  name: String!
}

# from B.graphql
extend type Person {
  hasCar: Boolean!
}

# from C.graphql
extend type Person {
  hasLicense: Boolean!
}
```

**Comment by mununki** [comment]
In fact, if the goal is to merge into one schema, I wonder if it would be more consistent to merge the fields in the object extension as well.
```graphql
# after merging
type Person implements Node {
  id: ID!
  createTime: Time!
  updateTime: Time!
  name: String!
  hasCar: Boolean!,
  hasLicense: Boolean!
}
```

**Comment by mununki** [comment]
I think I fix this issue in v0.2.13. Can you test it?

**Comment by vitorfalcaor** [comment]
Hey @mununki I just tested it and it worked, but not fully, it breaks in the scenario where the lib first loads the file with the "extend type" directive and then the file defining the actual type. For example, if I run:

```
go run github.com/mununki/gqlmerge --indent=2s graph/.graphql ../frontend/graph/schema.graphql
```

And the graph folder has the following files: `extendedSchema.graphl` and `schema.graphql`.

Then the merge fails with the message saying that the type has already been defined. I believe that happens because `extendedSchema` comes before `schema` alphabetically speaking. If I change the name of the first file to `zExtendedSchema`, then the merge works.

**Comment by mununki** [comment]
> Hey @mununki I just tested it and it worked, but not fully, it breaks in the scenario where the lib first loads the file with the "extend type" directive and then the file defining the actual type. For example, if I run:
> 
> ```
> go run github.com/mununki/gqlmerge --indent=2s graph/.graphql ../frontend/graph/schema.graphql
> ```
> 
> And the graph folder has the following files: `extendedSchema.graphl` and `schema.graphql`.
> 
> Then the merge fails with the message saying that the type has already been defined. I believe that happens because `extendedSchema` comes before `schema` alphabetically speaking. If I change the name of the first file to `zExtendedSchema`, then the merge works.

Oh, thank you for reporting! Can you open the separated issue? And please share the error cases of the schema sample.

**Comment by vitorfalcaor** [comment]
Done: https://github.com/mununki/gqlmerge/issues/50
