### ISSUE TITLE
Extend Type fails if type implements Node, depending on file alphabetical order

### ISSUE THREAD

**Issue by vitorfalcaor** [mununki/gqlmerge#50]
When extending a type that `implements Node` and if the file that extends the type comes before the file that declares the type in alphabetical order, then the merge fails.

Person.graphql
```graphql
type Person implements Node {
  name: String!
}
```

ExtendedPerson.graphql
```graphql
extend type Person {
  age: Int!
}
```

For the schemas above, since `ExtendedPerson` comes before `Person` in alphabetical order, the merge will fail. If we rename `ExtendedPerson` to `zExtendedPerson` it will come after `Person` in alphabetical order and the merge will succeed.

It's important to note that the order of the files only matters when the type `implements Node`, otherwise the merge succeeds as expected.

Repro command:

```
go run github.com/mununki/gqlmerge --indent=2s test/*.graphql test/t/s.graphql
```

Error:
```
🎉 [test/extendedPerson.graphql] Total 1 GraphQL files found!
🎉 [test/person.graphql] Total 1 GraphQL files found!
panic: lib.Error("Duplicated Types: Person(test/extendedPerson.graphql:1:12) and (test/person.graphql:1:5)")

goroutine 36 [running]:
github.com/mununki/gqlmerge/lib.errorf(...)
        /go/pkg/mod/github.com/mununki/gqlmerge@v0.2.13/lib/parse.go:14
github.com/mununki/gqlmerge/lib.(*Schema).MergeTypeName(0x1400012e1c0, 0x0?)
        /go/pkg/mod/github.com/mununki/gqlmerge@v0.2.13/lib/schema.go:565 +0x6ec
created by github.com/mununki/gqlmerge/lib.mergeSchemas in goroutine 1
        /go/pkg/mod/github.com/mununki/gqlmerge@v0.2.13/lib/merge.go:77 +0x88c
```

**Comment by mununki** [comment]
Thank you for opening an issue with a detailed explanation.

**Comment by mununki** [comment]
Can you try with newly relased v0.2.14?

**Comment by vitorfalcaor** [comment]
Thank you @mununki it worked perfectly!

**Comment by mununki** [comment]
> Thank you @mununki it worked perfectly!

Thank you!
