### ISSUE TITLE
federation:merging same types fails - duplication type error

### ISSUE THREAD

**Issue by ilterpehlivan** [mununki/gqlmerge#54]
I have 2 different graphql schema and I am using federation to combine their results. Therefore I have same type in 2 different schema. While merging those 2 giving `duplication error`

Here is the files that I have:

**test1.graphql**
```
type Product {
    id: ID!
    name: String
}
```

**test2.graphql**
```
type Product {
    id: ID  --> external ID is optional from introspect
    description: String
}
```

My code to merge them:
```
func main() {
	superSchema := gql.Merge(" ", "./tmp/test1.graphql", "./tmp/test2.graphql")
	fmt.Println(superSchema)
}
```

**Expected output:**
```
type Product {
    id: ID!
    name: String
    description: String
}
```

Error:

```
[tmp/test1.graphql] Total 1 GraphQL files found!
🎉 [tmp/test2.graphql] Total 1 GraphQL files found!
panic: lib.Error("Duplicated Types: id(tmp/test1.graphql:2:0) and (tmp/test2.graphql:2:0)")

goroutine 20 [running]:
github.com/mununki/gqlmerge/lib.errorf(...)
	/Users/user/go/pkg/mod/github.com/mununki/gqlmerge@v0.2.15/lib/parse.go:14
github.com/mununki/gqlmerge/lib.mergeFields({0xc0001040f0, 0x2, 0x2}, {0xc0001041d0, 0x2, 0x0?})
	/Users/user/go/pkg/mod/github.com/mununki/gqlmerge@v0.2.15/lib/schema.go:805 +0x639
github.com/mununki/gqlmerge/lib.(*Schema).MergeTypeName(0xc00012c1c0, 0x0?)
	/Users/user/go/pkg/mod/github.com/mununki/gqlmerge@v0.2.15/lib/schema.go:581 +0x538
created by github.com/mununki/gqlmerge/lib.mergeSchemas in goroutine 1
	/Users/user/go/pkg/mod/github.com/mununki/gqlmerge@v0.2.15/lib/merge.go:77 +0xa19
exit status 2
```

**Comment by mununki** [comment]
First of all, I don't know much about how federation works. But to me, type Product in test1 and type Product in test2 read as totoally different types. I'm not sure what to do with the merge in this case.
If it is merged to the expected output, the API with the test2 schema will be able to return a null id value, and the schema will break the promise of the actual API's response.

**Comment by ilterpehlivan** [comment]
thank you for the answer @mununki , you are right about this :) I will close the issue, sorry for the trouble

**Comment by mununki** [comment]
> thank you for the answer @mununki , you are right about this :) I will close the issue, sorry for the trouble

No problem. Thank you for reporting!
