### ISSUE TITLE
Directives Parsing

### ISSUE THREAD

**Issue by 3timeslazy** [mununki/gqlmerge#6]
Hi! Project falls on the follow example:
```graphql
type Mutation {
    createUserOld(user: User!): User! @deprecated (reason: "Use 'createUserNew' instead")
    createUserNew(user: User!): User!
}
```

**Comment by mununki** [comment]
I will work on it. Thanks!

**Comment by mununki** [comment]
I've just released PR #8 to master branch. Please try again with it and let me know if you have any further error.

**Comment by 3timeslazy** [comment]
Works fine! Thank for such quick response!

**Comment by mununki** [comment]
Thank you is mine. I can build more codes for unexpected schema examples thanks to your issues.
