### ISSUE TITLE
Parse fail cases

### ISSUE THREAD

**Issue by 3timeslazy** [mununki/gqlmerge#7]
Hi! Project falls on the follow examples:
* There are no mutation arguments (queries works fine)
```graphql
type Mutation {
    doSmth: OK!
}
```
* Pass list as mutation (query) argument
```graphql
type Mutation {
    createList(list: [Item]): OK!
}
```
* Interface has method
```graphql
interface Admin {
    ban(userID: ID!): OK!
}
```

**Comment by mununki** [comment]
Wonderful! Thank you for raising issues. I'll work on it.

**Comment by mununki** [comment]
I've just released PR #8 to master branch. Please try again with it and let me know if you have any further error.

**Comment by 3timeslazy** [comment]
Everything works! Thanks!

**Comment by mununki** [comment]
Sounds great! I'm not sure why `contributor` doesn't show you as a contributor in the front page of this repo. I guess it is just a time delay.

I hope to have your further issues or suggestions soon.
